<?php $this->layout('layout', [
  'meta_title' => 'Swimming Resources | SwimSnap',
  'meta_description' => 'Community-shared national, zone, and LSC swimming websites.',
  'meta_canonical_url' => $base_url . '/resources/'
]) ?>
<?php session_start(); $flash = $_SESSION['resource_flash'] ?? null; unset($_SESSION['resource_flash']); ?>

<nav aria-label="breadcrumb"><ol class="breadcrumb mb-4"><li class="breadcrumb-item"><a href="<?= $base_url ?>/">Home</a></li><li class="breadcrumb-item active">Resources</li></ol></nav>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
  <div><h1 class="mb-1"><i class="bi bi-bookmarks me-1"></i> Swimming Resources</h1><p class="text-muted mb-0">Helpful websites for the national, zone, and LSC swimming community.</p></div>
  <div class="btn-group" role="group" aria-label="Resource view"><button class="btn btn-outline-primary active" data-resource-view="cards"><i class="bi bi-grid-3x3-gap"></i> Cards</button><button class="btn btn-outline-primary" data-resource-view="list"><i class="bi bi-list-ul"></i> List</button></div>
</div>
<?php if ($flash): ?><div class="alert alert-<?= htmlspecialchars($flash[0]) ?>"><?= htmlspecialchars($flash[1]) ?></div><?php endif; ?>

<section class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5">Share a website</h2><form method="post" action="<?= $base_url ?>/resources/create.php" id="resource-form" class="row g-3"><div class="col-md-6"><label class="form-label" for="resource-url">Website URL</label><input class="form-control" id="resource-url" name="url" type="url" placeholder="https://www.example.org" required></div><div class="col-md-2"><label class="form-label" for="resource-category">Level</label><select class="form-select" id="resource-category" name="category"><option value="national">National</option><option value="zone">Zone</option><option value="lsc">LSC</option></select></div><div class="col-md-2 resource-region-field d-none"><label class="form-label" for="resource-zone">Zone</label><select class="form-select" id="resource-zone" name="zone_code"><option value="">Select zone</option><?php foreach ($regions as $code => $region): ?><option value="<?= $code ?>"><?= htmlspecialchars($region[0]) ?></option><?php endforeach; ?></select></div><div class="col-md-2 resource-lsc-field d-none"><label class="form-label" for="resource-lsc">LSC</label><select class="form-select" id="resource-lsc" name="lsc_code" disabled><option value="">Select LSC</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100" type="submit">Post link</button></div><div id="resource-details" class="d-none col-12"><div class="row g-3"><div class="col-md-5"><label class="form-label" for="resource-title">Title</label><input class="form-control" id="resource-title" name="title" maxlength="180"></div><div class="col-md-7"><label class="form-label" for="resource-description">Description</label><textarea class="form-control" id="resource-description" name="description" maxlength="500" rows="2"></textarea></div></div></div></form><div id="resource-preview" class="d-none mt-3"></div><p id="resource-preview-message" class="small text-muted mb-0 mt-2">Title, description, and website preview are generated when you paste a link. You can edit the title and description before posting.</p></div></section>

<?php if (!$resources): ?><div class="text-center border rounded p-5 text-muted">No resources yet. Share the first helpful swimming website.</div><?php else: ?>
<div id="resource-cards" class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4"><?php foreach ($resources as $resource): ?><div class="col"><article class="card h-100 shadow-sm resource-card"><img src="<?= htmlspecialchars($resource['screenshot_url'] ?? resource_screenshot_url($resource['url'])) ?>" class="card-img-top resource-shot" alt="Website preview" onerror="this.onerror=null;this.src='<?= $base_url ?>/images/logo.png';this.classList.add('resource-logo-fallback')"><div class="card-body d-flex flex-column"><span class="badge text-bg-primary align-self-start text-uppercase mb-2"><?= htmlspecialchars($resource['category']) ?></span><h2 class="h5"><a class="stretched-link text-decoration-none" href="<?= htmlspecialchars($resource['url']) ?>" target="_blank" rel="noopener noreferrer"><?= htmlspecialchars($resource['title']) ?></a></h2><p class="text-muted small line-clamp-3 mb-0"><?= htmlspecialchars(($resource['description'] ?? '') ?: parse_url($resource['url'], PHP_URL_HOST)) ?></p></div><div class="card-footer bg-white small text-muted d-flex justify-content-between align-items-center"><span class="text-truncate"><i class="bi bi-link-45deg"></i> <?= htmlspecialchars(parse_url($resource['url'], PHP_URL_HOST)) ?></span><a class="resource-edit-link ms-2" href="<?= $base_url ?>/resources/edit.php?url=<?= rawurlencode($resource['url']) ?>">Edit</a></div></article></div><?php endforeach; ?></div>
<div id="resource-list" class="d-none list-group shadow-sm"><?php foreach ($resources as $resource): ?><a class="list-group-item list-group-item-action d-flex gap-3 align-items-center" href="<?= htmlspecialchars($resource['url']) ?>" target="_blank" rel="noopener noreferrer"><img src="<?= htmlspecialchars($resource['image_url'] ?: resource_screenshot_url($resource['url'])) ?>" class="resource-list-image" alt="" onerror="this.onerror=null;this.src='<?= $base_url ?>/images/logo.png';this.classList.add('resource-logo-fallback')"><span class="flex-grow-1"><span class="badge text-bg-primary text-uppercase me-2"><?= htmlspecialchars($resource['category']) ?></span><strong><?= htmlspecialchars($resource['title']) ?></strong><small class="d-block text-muted line-clamp-2"><?= htmlspecialchars($resource['description'] ?: parse_url($resource['url'], PHP_URL_HOST)) ?></small></span><i class="bi bi-box-arrow-up-right"></i></a><?php endforeach; ?></div><?php endif; ?>

<script>
(() => { const input=document.querySelector('#resource-url'), preview=document.querySelector('#resource-preview'), message=document.querySelector('#resource-preview-message'), level=document.querySelector('#resource-category'), zone=document.querySelector('#resource-zone'), lsc=document.querySelector('#resource-lsc'), regions=<?= json_encode($regions) ?>; let timer;
  const fallbackImage = '<?= $base_url ?>/images/resource-bg.png';
  document.querySelectorAll('img[src*="image.thum.io"]').forEach(image => { image.onerror = null; image.src = fallbackImage; });
  new MutationObserver(records => records.forEach(record => { const image = record.target; if (image.classList.contains('resource-logo-fallback') && image.src !== fallbackImage) image.src = fallbackImage; })).observe(document.body, {subtree:true, attributes:true, attributeFilter:['class']});
  function updateRegions() { const isNational=level.value==='national', isLsc=level.value==='lsc'; document.querySelector('.resource-region-field').classList.toggle('d-none',isNational); document.querySelector('.resource-lsc-field').classList.toggle('d-none',!isLsc); lsc.disabled=!isLsc; if (!isLsc) lsc.value=''; }
  function updateLscs() { lsc.innerHTML='<option value="">Select LSC</option>'; const entries=regions[zone.value]?.[1]||{}; Object.entries(entries).forEach(([code,name])=>lsc.add(new Option(name,code))); } level.addEventListener('change',updateRegions); zone.addEventListener('change',updateLscs); updateRegions();
  input.addEventListener('input', () => { clearTimeout(timer); preview.classList.add('d-none'); if (!input.value.trim()) return; timer=setTimeout(async () => { message.textContent='Generating website preview…'; try { const res=await fetch('<?= $base_url ?>/resources/preview.php?url='+encodeURIComponent(input.value)); const data=await res.json(); if (!data.ok) throw new Error(data.message); const p=data.preview; document.querySelector('#resource-title').value=p.title; document.querySelector('#resource-description').value=p.description; document.querySelector('#resource-details').classList.remove('d-none'); preview.innerHTML=`<div class="resource-inline-preview"><img src="${p.screenshot_url}" alt="Website screenshot" onerror="this.onerror=null;this.src='<?= $base_url ?>/images/logo.png';this.classList.add('resource-logo-fallback')"><div><strong>${escapeHtml(p.title)}</strong><p class="small text-muted mb-0">${escapeHtml(p.description || p.url)}</p></div></div>`; preview.classList.remove('d-none'); message.textContent='Review or edit the generated title and description, then post.'; } catch (err) { message.textContent=err.message || 'Preview unavailable.'; } }, 550); });
  function escapeHtml(value) { const node=document.createElement('div'); node.textContent=value; return node.innerHTML; }
  document.querySelectorAll('[data-resource-view]').forEach(button => button.addEventListener('click', () => { const cards=button.dataset.resourceView==='cards'; document.querySelector('#resource-cards')?.classList.toggle('d-none', !cards); document.querySelector('#resource-list')?.classList.toggle('d-none', cards); document.querySelectorAll('[data-resource-view]').forEach(b => b.classList.toggle('active', b===button)); }));
})();
document.querySelectorAll('#resource-list > a').forEach(link => {
  const edit = document.createElement('button');
  edit.type = 'button'; edit.className = 'btn btn-sm btn-outline-primary resource-list-edit'; edit.textContent = 'Edit';
  edit.addEventListener('click', event => { event.preventDefault(); event.stopPropagation(); window.location.href = '<?= $base_url ?>/resources/edit.php?url=' + encodeURIComponent(link.href); });
  link.appendChild(edit);
});
</script>
<?php if (!empty($recaptcha_site_key)): ?>
<script src="https://www.google.com/recaptcha/api.js?render=explicit" defer></script>
<script>
window.addEventListener('load', () => {
  const form = document.querySelector('#resource-form');
  if (!form || !window.grecaptcha) return;
  const holder = document.createElement('div'); form.appendChild(holder);
  const widget = grecaptcha.render(holder, {sitekey: '<?= htmlspecialchars($recaptcha_site_key) ?>', size: 'invisible', callback: token => { const input = document.createElement('input'); input.type = 'hidden'; input.name = 'g-recaptcha-response'; input.value = token; form.appendChild(input); form.submit(); }});
  form.addEventListener('submit', event => { if (!form.querySelector('[name="g-recaptcha-response"]')) { event.preventDefault(); grecaptcha.execute(widget); } });
});
</script>
<?php endif; ?>
